export const BlockConstant = {
  ADD: "ADD_BLOCK",
  EDIT_BLOCK: "EDIT_BLOCK",
  DELETE_BLOCK: "DELETE_BLOCK",
  INSERT_STEP: "INSERT_STEP",
  EDIT_STEP: "EDIT_STEP",
  SHIFT_STEP: "SHIFT_STEP",
  DELETE_STEP: "DELETE_STEP",
};

export const VariableConstant = {
  ADD_VARIABLE: "ADD_VARIABLE"
}